# Generated by Django 3.1.11 on 2021-05-24 17:11

import django.core.serializers.json
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=500)),
                ('platform', models.CharField(max_length=250)),
                ('platform_id', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('url', models.CharField(max_length=500)),
                ('application_url', models.CharField(max_length=500)),
                ('raw_json', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
